version: '3'
services:
  redisserver:
    image: redis
    container_name: redisserver
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--bind"
      - "redisserver"
      - "--port"
      - "6379"

  githubprofiler:
    depends_on:
      - redisserver
    build:
      context: ./profiler
    container_name: githubprofiler
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      GITHUB_TOKEN: ghp_token
      REDIS_URL: redis://redisserver:6379
      REDIS_PORT: 6379

  nginx:
    container_name: nginx
    depends_on:
      - githubprofiler
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
